worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 127.0.0.1:9441 ssl;
        ssl_certificate     examples/tls/cert.pem;
        ssl_certificate_key examples/tls/key.pem;
        location / {
            return 200 "backend-tls1\n";
        }
    }
}
