worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 127.0.0.1:9092;
        location / {
            return 200 "hello from qwewginx h2\n";
        }
    }
}
