worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream backend {
        server 127.0.0.1:9441;
        server 127.0.0.1:9442;
    }

    server {
        listen 127.0.0.1:9450 ssl;
        ssl_certificate     examples/tls/cert.pem;
        ssl_certificate_key examples/tls/key.pem;
        location / {
            proxy_ssl_verify off;
            proxy_pass https://backend;
        }
    }
}
