worker_processes 1;
events {
    worker_connections 1024;
}
http {
    upstream backend {
        server 127.0.0.1:9091;
    }
    server {
        listen 127.0.0.1:9443 ssl;   # use 443 with root/setcap if you want
        ssl_certificate     examples/tls/cert.pem;
        ssl_certificate_key examples/tls/key.pem;
        location / {
            proxy_pass http://backend;
        }
    }
}