worker_processes 1;

events {
    worker_connections 1024;
}

# tcp relay — e.g. minecraft java edition (raw tcp, default port 25565)
stream {
    server {
        listen 127.0.0.1:25565;
        proxy_pass 127.0.0.1:25566;
    }
}
