worker_processes 1;

events {
    worker_connections 1024;
}

http {
    server {
        listen 127.0.0.1:443 ssl;
        ssl_certificate ../../examples/tls/cert.pem;
        ssl_certificate_key ../../examples/tls/key.pem;
        location / {
            return 200 "hello from qwewginx tls\n";
        }
    }
    server {
        listen 127.0.0.1:80;
        location / {
            return 200 "hello from qwewginx (no tls!)\n";
        }
    }
}
